[workspace]
resolver = "2"
members = [
    "babbelaar",
    "builtin",
    # Disable the compiler as it requires building LLVM
    # "compiler",
    "interpreter",
    "lsp",
    "tests",
]
default-members = ["interpreter"]
