[package]
name = "babbelaar-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
babbelaar = { path = "../babbelaar" }
babbelaar-builtin = { path = "../builtin" }

inkwell = { git = "https://github.com/TheDan64/inkwell", rev = "5c9f7fcbb0a667f7391b94beb65f1a670ad13221", features = ["llvm18-0"] }
log = "0.4"

[dev-dependencies]
rstest = "0.21"
