name: Release

on:
  push:
    branches: [ "release" ]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            archive: zip
            os: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}